# AI Hub 平台监控服务
# Week 6 Day 4: 系统监控和日志配置

version: '3.8'

services:
  # Prometheus 指标收集
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-hub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus-rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - ai-hub-network
    restart: unless-stopped
    depends_on:
      - ai-hub-backend

  # Grafana 可视化
  grafana:
    image: grafana/grafana:latest
    container_name: ai-hub-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - ai-hub-network
    restart: unless-stopped
    depends_on:
      - prometheus

  # Elasticsearch 日志存储
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ai-hub-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ai-hub-network
    restart: unless-stopped

  # Kibana 日志可视化
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: ai-hub-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ai-hub-network
    restart: unless-stopped
    depends_on:
      - elasticsearch

  # Logstash 日志处理
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: ai-hub-logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./monitoring/logstash/pipeline:/usr/share/logstash/pipeline
      - ./monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - ai-hub-network
    restart: unless-stopped
    depends_on:
      - elasticsearch

  # Redis 监控数据缓存
  redis-monitor:
    image: redis:7-alpine
    container_name: ai-hub-redis-monitor
    ports:
      - "6380:6379"
    volumes:
      - redis_monitor_data:/data
    networks:
      - ai-hub-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass your_redis_password

  # Redis Commander (Redis管理界面)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ai-hub-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis-monitor:6379:0:your_redis_password
    networks:
      - ai-hub-network
    restart: unless-stopped
    depends_on:
      - redis-monitor

  # Node Exporter 系统指标
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ai-hub-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - ai-hub-network
    restart: unless-stopped

  # cAdvisor 容器指标
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ai-hub-cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - ai-hub-network
    restart: unless-stopped

  # AlertManager 告警管理
  alertmanager:
    image: prom/alertmanager:latest
    container_name: ai-hub-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    networks:
      - ai-hub-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_monitor_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  ai-hub-network:
    external: true